### ISSUE TITLE
Unique starID needed for constant stars and fakerrlyr

### ISSUE THREAD

**Issue by jsk389** [tasoc/starclass#10]
If the star is a constant star or fakerrlyr then the star ID is set to -1 because it doesn't have a KIC number. But this has an unintended side effect that in the RF_GC classifier only one feature file is created for the entire class (it keeps getting overwritten) and so the classifier actually appears to only trains on one constant class example! I don't know, however, if this also affects SLOSH however.

Would it be possible to give the constant stars a unique identifier so this doesn't happen?

**Comment by rhandberg** [comment]
Actually it should never be assumed that the `starid` is a unique number. In principle, there could be several lightcurves from the same `starid`, e.g. from FFIs and TPF. What is guaranteed to be unique is the `priority`... I know, then name doesn't make much sense here, but it is a unique number for each dataset, and the name comes from the photometry pipeline where it is used as the order in which to process targets.

If any of the classifiers uses `starid`, I would encourage to change it to `priority` instead.

**Comment by DJArmstrong** [comment]
RFGC now runs on priority instead of starid (PR#15). Leaving this open because I guess there are other dependencies elsewhere in the code?
