### ISSUE TITLE
BaseClassifier: data_dir assigned but not created

### ISSUE THREAD

**Issue by jsk389** [tasoc/starclass#12]
In BaseClassifier there is the line ```self.data_dir=os.path.abspath(os.path.join(os.path.dirname(__file__), 'data', level)) ```
which assigns a data directory, however if it doesn't exist it does not automatically create the directory. I imagine this would be a useful thing for it to do?! Otherwise the classifiers will crash later down the line.

**Comment by DJArmstrong** [comment]
Fixed by PR#15
