### ISSUE TITLE
Meta-classifier training fails when trying to predict for second classifier

### ISSUE THREAD

**Issue by jsk389** [tasoc/starclass#30]
When training the meta-classifier it successfully predicts on the test-set for the first classifier, but as soon as it gets to the second classifier I get this error.

```
Traceback (most recent call last):
  File "run_training.py", line 94, in <module>
    stcl.test(tset_fold, save=True, save_func=tm.save_result)
  File "starclass/starclass/BaseClassifier.py", line 178, in test
    save_func(res)
  File "starclass/starclass/taskmanager.py", line 224, in save_result
    self.conn.commit()
sqlite3.OperationalError: database is locked
```

**Comment by rhandberg** [comment]
Are you certain that you are not running several processes that are working on the same training set?

**Comment by jsk389** [comment]
As far as I know I am not, but I can check this tomorrow to be sure! I've tried searching for any files in case the database is corrupted or something hasn't been cleared, but couldn't find anything.

**Comment by jsk389** [comment]
Even when I've cleared everything and run it fresh (no features of datasets saved) I still end up with this same issue. Which always occurs when predicting on the first fold of the second classifier.

**Comment by rhandberg** [comment]
After pulling in your changes, I was (finally) able to reproduce the error... I have no idea what is causing it yet, but I'm working on it...

**Comment by jsk389** [comment]
Even if I run from commit ab168b5db3fe6a61815b514a6b3a1186006da0b0 I still get exactly the same issue. I wonder if it's to do with rerunning it after it has crashed? Would that give an error like that?

**Comment by rhandberg** [comment]
The bug should be fixed by https://github.com/tasoc/starclass/commit/e509dd42dd88f8c9371bdc3e29238c491a96020f

It's not pretty... It's actually rather nasty code... But I think it works...

@jsk389 will you do some testing and see if we can close this issue?

**Comment by jsk389** [comment]
It appears to be running through the second classifier, so I think it's worked. Thanks so much @rhandberg for the fix! I will have a look at the database and see what's written out tomorrow.

**Comment by jsk389** [comment]
It works perfectly!
