### ISSUE TITLE
Feeding classifier probabilities to the meta-classifier

### ISSUE THREAD

**Issue by jsk389** [tasoc/starclass#31]
All the classifiers can be successfully trained and the results saved to the database. The issue now is that before the meta-classifier can be trained the probabilities from each classifier need to be given to it. From what I can see this isn't possible at the moment @rhandberg?

**Comment by rhandberg** [comment]
Aren't they under the `'other_classifiers'` key of the features dict? They should be...

**Comment by jsk389** [comment]
All the rows are empty. As far as I can see the star class table is never merged with the feature table ~ line 121 of task manager.py  as neither diagnostics or todo list contain the probabilities. https://github.com/tasoc/starclass/blob/e509dd42dd88f8c9371bdc3e29238c491a96020f/starclass/taskmanager.py#L121-L138

**Comment by rhandberg** [comment]
It actually happens a few lines further down... Have you looked in the TODO-file if the "starclass" table actually contains anything?
https://github.com/tasoc/starclass/blob/e509dd42dd88f8c9371bdc3e29238c491a96020f/starclass/taskmanager.py#L149-L162

**Comment by jsk389** [comment]
Ah yes my mistake! I've checked the starclass table and it contains all the info it should. I'm not sure why it isn't finding anything. It just returns rows as None.

**Comment by jsk389** [comment]
If I comment out the lines checking row count then it works and the probabilities are parsed to the metaclassifier.
https://github.com/tasoc/starclass/blob/e509dd42dd88f8c9371bdc3e29238c491a96020f/starclass/taskmanager.py#L153-L156
The row count comes to -1 for some reason which is causing the problem.

**Comment by rhandberg** [comment]
Yes, I've come to the same conclusion... It comes from something funky in the SQLite database engine, that it can't actually figure out how many rows are returned... I have fixed it in my local copy and will push up a fix soon... I'm at the same time looking into returning the classes as actual `StellarClasses` objects instead of keys to those Enums...

**Comment by jsk389** [comment]
Ok,, that sounds strange but at least it's a simple enough fix this time. That sounds good to me!

**Comment by rhandberg** [comment]
Should be fixed in the latest commit I did
