### ISSUE TITLE
Optimize MPI

### ISSUE THREAD

**Issue by jeraud** [tasoc/starclass#77]
We should optimize the MPI settings, because currently the code does not scale well to multiple nodes.

**Comment by rhandberg** [comment]
I am going to need some more information!

Could you please edit the description of the bug using the following formatting, which should hopefully make easier to pinpoint what the exact issue is.

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Run this command '...'
2. See error '....'

**Expected behavior**
A clear and concise description of what you expected to happen.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Python version: [e.g. 3.6.4]
 - Version [e.g. 5.0.1]

**Additional context**
Add any other context about the problem here.
```

**Comment by jeraud** [comment]
**Describe the bug**
The code runs much slower when scaled to multiple nodes.

**To Reproduce**
1. Specify the cores and nodes in the script `#PBS nodes=4:ppn=35` (or put it directly in the command underneath)
2. Run `mpiexec python /starclass/run_starclass_mpi.py -t keplerq9v3  /data/kasoc_q9/`

**Issue**
The code will not scale well to multiple nodes, it actually goes slower than running it on a single node. Even when running the code on 1 node with multiple cores, I still have the feeling that it is not scaling in linear time at all.

**System**
- Linux
- Python 3.7.6
(but I don't think it is system dependent, as I've tried running it on different linux machines)

Additionally, this code also sometimes crashes after a while due to a memory overflow, maybe this has something to do with it. I still have to do some memory-profiling for that.

**Comment by rhandberg** [comment]
Do you have the TODO-file from an example run? Is it the actual processing time or is it the "worker_wait_time" that gets big? How are your nodes inter-connected? Infiniband?

The memory issue depends a lot on the actual system you are running on. If you specify 35 processes on a node, remember that this will spawn 35 instances of e.g. Tensorflow or xgboost at the same time, which can be quite memory-intensive!
