### ISSUE TITLE
DISC: project structure

### ISSUE THREAD

**Issue by Xylambda** [tasoc/starclass#88]
Hi,

first of all, thanks for the package.

I would like to suggest some changes to the overall structure of the library since I think we could all benefit from them. Apologies for not following the issue template, but it does not really fit into what I want to say.

## Problem: Requirements and setup
Right now, the library is installed via `pip -r requirements.txt` and the requirements file is used to install all dependencies. This is not the standard way of installing packages (even if some big libraries do it this way). The standard way of doing this is by creating a `setup.py` file that contains all **minimum** dependencies **without upper and lower bound unless necessary**. 

The requirements file is used to mimic the environment in which the library was developed, not to install the library itself. That is, it should be needed only if one wants to write code for the library and needs to work with the same versions as the rest of developers.

If you install always with `requirements.txt` you will end up with incompatible dependencies with other libraries. e.g. What if I need a lower version of TensorFlow? (and yes, this also may happen using the setup.py if you use upper and lower bounds, but it is less likely).

### Solution

* Add a setup file with all requirements, specifying upper and lower bounds **only when necessary**. A possible example:

```python
from setuptools import setup, find_packages
from os import path

here = path.abspath(path.dirname(__file__))

with open(path.join(here, 'README.md'), encoding='utf-8') as f:
    long_description = f.read()

setup(
    name='starclass',
    description='Stellar classification in Python',
    long_description=long_description,
    long_description_content_type='text/markdown',
    url='https://github.com/tasoc/starclass,
    author='TASOC',
    classifiers=[
        'Development Status :: 3 - Alpha',
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Build Tools',
        'License :: OSI Approved :: MIT License',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3.5',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3 :: Only',
    ],
    python_requires='>=3.5, <4',
    install_requires=[
        "numpy",
        "matplotlib",
        "scipy",
        "astropy",
        "lightkurve >= 1.7.0, < 2.0",
        "scikit-learn",
        "Bottleneck",
        "requests",
        "tensorflow",
        "xgboost",
        "tqdm",
        "pyentrp",
        "h5py",
        "shap"
    ],
)
```

* Add `requirements-dev.txt` (in case someone wants to replicate the environment without installing dev tools) and `requirements-docs.txt`. [Example](https://github.com/Xylambda/kalmanfilter).

## Problem: Structure
1. Right now, the library uses `lib_name/lib_name/code` as the main structure. While this is not wrong, the current standard way of doing this is by using a `lib_name/src/lib_name/code` structure.
2. The are code files outside the `lib_name` folder: `run_*.py` files. This is definitely not a good practice.
3. `notes` folder has a weird name.
4. Classifiers should be grouped into one module instead of being spread.
5. [Some methods](https://github.com/tasoc/starclass/blob/devel/starclass/io.py#L128) and [files](https://github.com/tasoc/starclass/blob/devel/starclass/StellarClasses.py) are camel case and do not follow PEP8 naming conventions.
6. Conventions (StellarClasses, constants, etc) should be grouped into one file/module.
7. matplotlib styles and plotting utils should be grouped into one module.
8. There should be a preprocessing module to group all utilities related to feature extraction that are not specific to a classifier.
9. Move files to where they belong. e.g. [this file](https://github.com/tasoc/starclass/blob/devel/starclass/example/ExampleClassifier.py)
10. `convenience.py`, `download_cache.py`, `exceptions.py`, `taskmanager.py`, `utilities.py` and maybe `todolist.py` should be grouped into a `utils` module.

### Solution
1. Follow [example](https://github.com/Xylambda/kalmanfilter).
2. Implement a CLI or move the code into a specific module **inside** library folder.
3. Rename `notes` to `examples`.
4. Create module `models` and move all classifiers and `BaseClassifier` there.
5. Rename **all** methods and files in order to follow PEP8. e.g.: `loadPickle` to `load_pickle`. `SLOSH` to `slosh`.
6. Group conventions into one file or module. [Example](https://github.com/Xylambda/torchfitter/blob/master/src/torchfitter/conventions.py).
7. Group `plot.py` and matplotlib styles into one module. e.g. `plotting`.
8. Create and fill `preprocessing` module.
9. Move examples files to the `examples`/`notes` folder.
10. Group aforementioned files into `utils` module.

------

I sincerely hope this message finds you well and you take the time to consider these proposals. I am more than keen to help to implement these suggestions (if you want and need) since I need to use the library for my Master's degree thesis (at first I was planning to create my own library but I decided to contribute to a bigger project).

Waiting for your comments,

Alejandro.

**Comment by rhandberg** [comment]
This code is part of a much larger structure, which this fits into as a module.

All due respect to "best practices" or other such recommendations, but the way the code structure is currently set up follows our own "best practices" - which may be flawed, but so be it.

Closing this now.

**Comment by Xylambda** [comment]
Thanks for taking the time to read this and give me an answer.

Researchers need to be aware that code is public and that **they are not over the best practices** that everyone follows in software engineering, because they are best practices constructed over time by a lot of knowledgeable people to make **code more readable, usable, maintainable and faster**. Otherwise, we end up with another random bad repository that no one can use appropriately except the authors and some of their colleagues.

I hope all goes well for you and your team in the future and that you reconsider the way you write code, because you clearly need to reconsider it. 

Regards,
Alejandro.
